import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@components/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Links Redes Sociales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cover bg-center h-screen" style={{backgroundImage: "url('/Fondo-links.jpg')"}}>
        <div className={styles.container}>
          <div className='w-20'>
            <img src="https://scontent.fmex26-1.fna.fbcdn.net/v/t39.30808-6/317494435_5695746437173338_5107786524602904042_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=09cbfe&_nc_eui2=AeESEaEhfB3vt24rqwt5CuHHOciCOpr3ldQ5yII6mveV1N7dm13oC22xF7HPJG5py_HbbdFiZ27xe1ewEdlA9jDY&_nc_ohc=eKXdJyovIYkAX-3q51i&_nc_ht=scontent.fmex26-1.fna&oh=00_AfB1YEI4WGQg2KVjm75RqA-1c3efKcOaypdQcuPsiCgTBg&oe=6430F886" alt="Imagen de perfil tomada de mi facebook" />
          </div>
          <div className='w-20'>
            <h1>The Pichard</h1>
            <a href='' ><button className=''> facebook</button></a>
            <a href='' ><button className=''> Instagram</button></a>
            <a href='' ><button className=''> twich</button></a>
            <a href='' ><button className=''> Hibhub</button></a>
            <a href='' ><button className=''> Tweteer</button></a>
          </div>
        </div>
      </main>
    </>
  )
}
